spring.application.name: 'spring-cloud-zuul-gateway-demo'
spring.profiles.active: development

app.name: spring-cloud-zuul-gateway-demo
app.description: a spring-cloud + zuul demo app

server.port: 8652
server.use-forward-headers: true
server.compression.enabled: true

management.port: 9652
management.context-path: /

endpoints.jmx.domain: spring-cloud-zuul-gateway-demo
endpoints.jmx.unique-names: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/

#spring.boot.admin.url: http://localhost:9080

# LOGGING
logging.path: ./var/log
logging.file: application.log
logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO
